//===- Dialect.td - TToy dialect definitions ----------*- tablegen -*-===//
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// Defines the TToy dialect.
//
//===----------------------------------------------------------------------===//

#ifndef TTOY_DIALECT
#define TTOY_DIALECT

include "Ops.td"
include "mlir/IR/DialectBase.td"

#endif // 