//===- Dialect.td - Etoy dialect definitions ----------*- tablegen -*-===//
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// Defines the Etoy dialect.
//
//===----------------------------------------------------------------------===//

#ifndef ETOY_DIALECT
#define ETOY_DIALECT

include "Ops.td"
include "mlir/IR/DialectBase.td"

#endif // 